apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grantsy.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grantsy.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ toYaml .Values.config | indent 4 }}
